<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RpefO7P' shared service.

return $this->privates['.service_locator.RpefO7P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'versementRepository' => ['privates', 'App\\Repository\\VersementRepository', 'getVersementRepositoryService.php', true],
], [
    'versementRepository' => 'App\\Repository\\VersementRepository',
]);
