<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oSKvz7h' shared service.

return $this->privates['.service_locator.oSKvz7h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'tar' => ['privates', 'App\\Repository\\TarifsRepository', 'getTarifsRepositoryService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'tar' => 'App\\Repository\\TarifsRepository',
    'validator' => '?',
]);
