<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3wDcbJM' shared service.

return $this->privates['.service_locator.3wDcbJM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'transaction' => ['privates', '.errored..service_locator.3wDcbJM.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.3wDcbJM": it references class "App\\Entity\\Transaction" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'transaction' => 'App\\Entity\\Transaction',
    'validator' => '?',
]);
