<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partenaire extends \App\Entity\Partenaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'raisonSociale', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'ninea', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'adresseSociale', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'telephoneSiege', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'nomCompletPersonneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'emailPersonneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'emailSiege', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'telephoneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'comptes', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'imageName', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'cniPersonneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'adressePersonneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'status'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'raisonSociale', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'ninea', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'adresseSociale', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'telephoneSiege', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'nomCompletPersonneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'emailPersonneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'emailSiege', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'telephoneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'comptes', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'imageName', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'users', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'cniPersonneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'adressePersonneRef', '' . "\0" . 'App\\Entity\\Partenaire' . "\0" . 'status'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Partenaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonSociale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonSociale', []);

        return parent::getRaisonSociale();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonSociale(string $raisonSociale): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonSociale', [$raisonSociale]);

        return parent::setRaisonSociale($raisonSociale);
    }

    /**
     * {@inheritDoc}
     */
    public function getNinea(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNinea', []);

        return parent::getNinea();
    }

    /**
     * {@inheritDoc}
     */
    public function setNinea(string $ninea): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNinea', [$ninea]);

        return parent::setNinea($ninea);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseSociale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseSociale', []);

        return parent::getAdresseSociale();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseSociale(string $adresseSociale): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseSociale', [$adresseSociale]);

        return parent::setAdresseSociale($adresseSociale);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneSiege(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneSiege', []);

        return parent::getTelephoneSiege();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneSiege(int $telephoneSiege): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneSiege', [$telephoneSiege]);

        return parent::setTelephoneSiege($telephoneSiege);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCompletPersonneRef(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCompletPersonneRef', []);

        return parent::getNomCompletPersonneRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCompletPersonneRef(string $nomCompletPersonneRef): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCompletPersonneRef', [$nomCompletPersonneRef]);

        return parent::setNomCompletPersonneRef($nomCompletPersonneRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailPersonneRef(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailPersonneRef', []);

        return parent::getEmailPersonneRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailPersonneRef(string $emailPersonneRef): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailPersonneRef', [$emailPersonneRef]);

        return parent::setEmailPersonneRef($emailPersonneRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailSiege(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailSiege', []);

        return parent::getEmailSiege();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailSiege(string $emailSiege): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailSiege', [$emailSiege]);

        return parent::setEmailSiege($emailSiege);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneRef(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneRef', []);

        return parent::getTelephoneRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneRef(int $telephoneRef): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneRef', [$telephoneRef]);

        return parent::setTelephoneRef($telephoneRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getComptes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComptes', []);

        return parent::getComptes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCompte(\App\Entity\Compte $compte): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCompte', [$compte]);

        return parent::addCompte($compte);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCompte(\App\Entity\Compte $compte): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCompte', [$compte]);

        return parent::removeCompte($compte);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $imageFile = NULL): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$imageFile]);

        parent::setImageFile($imageFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageName', []);

        return parent::getImageName();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageName(string $imageName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageName', [$imageName]);

        return parent::setImageName($imageName);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\App\Entity\User $user): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\App\Entity\User $user): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCniPersonneRef(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCniPersonneRef', []);

        return parent::getCniPersonneRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setCniPersonneRef(int $cniPersonneRef): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCniPersonneRef', [$cniPersonneRef]);

        return parent::setCniPersonneRef($cniPersonneRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressePersonneRef(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressePersonneRef', []);

        return parent::getAdressePersonneRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressePersonneRef(string $adressePersonneRef): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressePersonneRef', [$adressePersonneRef]);

        return parent::setAdressePersonneRef($adressePersonneRef);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): \App\Entity\Partenaire
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

}
