<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9LvE3JX' shared service.

return $this->privates['.service_locator.9LvE3JX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'versement' => ['privates', '.errored..service_locator.9LvE3JX.App\\Entity\\Versement', NULL, 'Cannot autowire service ".service_locator.9LvE3JX": it references class "App\\Entity\\Versement" but no such service exists.'],
], [
    'versement' => 'App\\Entity\\Versement',
]);
