<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIFgBkIu\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIFgBkIu/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerIFgBkIu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerIFgBkIu\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerIFgBkIu\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'IFgBkIu',
    'container.build_id' => '277cad35',
    'container.build_time' => 1564956212,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIFgBkIu');
