<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZNJubNS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZNJubNS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZNJubNS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZNJubNS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZNJubNS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZNJubNS',
    'container.build_id' => '3dc5ef56',
    'container.build_time' => 1565471862,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZNJubNS');
