<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7VinNXy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7VinNXy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7VinNXy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7VinNXy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7VinNXy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7VinNXy',
    'container.build_id' => '649d0cdf',
    'container.build_time' => 1565288334,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7VinNXy');
